### ISSUE TITLE
successful installation but can't run

### ISSUE THREAD

**Issue by suredream** [samapriya/gee_asset_manager_addon#2]
Traceback (most recent call last):
  File "/usr/local/bin/geeadd", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2797, in <module>
    parse_requirements(__requires__), Environment()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 580, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (setuptools 1.1.6 (/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python), Requirement.parse('setuptools>=34.0.0'))

**Comment by samapriya** [comment]
As the error suggests
update setuptools
https://pypi.python.org/pypi/setuptools

the current version I am running is 36.6.0
