### ISSUE TITLE
Upload fail: google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials

### ISSUE THREAD

**Issue by arkanoid87** [samapriya/gee_asset_manager_addon#8]
```
2019-04-26 14:14:44,486 :: oauth2client.transport :: INFO :: Attempting refresh to obtain initial access_token
2019-04-26 14:14:44,486 :: oauth2client.client :: INFO :: Refreshing access_token
2019-04-26 14:14:48,383 :: google.auth.compute_engine._metadata :: INFO :: Compute Engine Metadata server unavailable onattempt 1 of 3
2019-04-26 14:14:48,430 :: google.auth.compute_engine._metadata :: INFO :: Compute Engine Metadata server unavailable onattempt 2 of 3
2019-04-26 14:14:51,433 :: google.auth.compute_engine._metadata :: INFO :: Compute Engine Metadata server unavailable onattempt 3 of 3
Traceback (most recent call last):
  File "/myenv/bin/geeadd", line 10, in <module>
    sys.exit(main())
  File "/myenv/local/lib/python2.7/site-packages/geeadd/geeadd.py", line 241, in main
    args.func(args)
  File "/myenv/local/lib/python2.7/site-packages/geeadd/geeadd.py", line 59, in upload_from_parser
    band_names=args.bands)
  File "/myenv/local/lib/python2.7/site-packages/geeadd/batch_uploader.py", line 89, in upload
    storage_client = storage.Client()
  File "/myenv/local/lib/python2.7/site-packages/google/cloud/storage/client.py", line 73, in __init__
    project=project, credentials=credentials, _http=_http
  File "/myenv/local/lib/python2.7/site-packages/google/cloud/client.py", line 223, in __init__
    _ClientProjectMixin.__init__(self, project=project)
  File "/myenv/local/lib/python2.7/site-packages/google/cloud/client.py", line 175, in __init__
    project = self._determine_default(project)
  File "/myenv/local/lib/python2.7/site-packages/google/cloud/client.py", line 190, in _determine_default
    return _determine_default_project(project)
  File "/myenv/local/lib/python2.7/site-packages/google/cloud/_helpers.py", line 186, in _determine_default_project
    _, project = google.auth.default()
  File "/myenv/local/lib/python2.7/site-packages/google/auth/_default.py", line 317, in default
    raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
```

**Comment by samapriya** [comment]
Removed upload functionality, for upload checkout github project [geeup](https://github.com/samapriya/geeup). This handles upload using selenium.
